# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  SONAR_TOKEN: $(sonarToken)

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - script: mvn clean compile
            displayName: 'Build'
          - script: mvn test
            displayName: 'Unit Test'
          - script: mvn install
            displayName: 'Jar generation'
  - stage: sonar
    dependsOn: build
    jobs:
      - job: sonar
        steps:
          - script: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=calculator-devops -Dsonar.login=$(SONAR_TOKEN)
            displayName: 'Sonar'


